[package]
name = "terminow"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
amgos-protocol = { path = "../amgos-protocol" }
libc = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
wgpu = "30.0.1"
winit = "0.30.13"
cosmic-text = "0.19.0"
pollster = "1.0.1"
