[workspace]
resolver = "2"
members = [
    "amgos-protocol",
    "amgos-system",
    "amgos-desktop",
    "filer/protocol",
    "filer/core",
    "filer/shell",
    "astrophage/protocol",
    "astrophage/core",
    "astrophage/shell",
    "terminow",
    "settings",
]

[workspace.package]
version = "0.0.1"
edition = "2021"
authors = ["AMG-OS Core Engineering Team"]
license = "Proprietary"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3.3"
sha2 = "0.10"
libc = "0.2"
flate2 = "1.0"
tar = "0.4"
zstd = "0.13"
