//! Permission and Signed Configuration State Management
//!
//! Process 1 owns and enforces system boundaries. Configuration state
//! is cryptographic and read-only to users. Changes require verification.

use serde::{Deserialize, Serialize};
use std::sync::{Arc, Mutex};

/// Structured signed configuration payload generated by Settings or Setup Wizard
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SignedSystemConfig {
    pub version: u32,
    pub user_name: String,
    pub locale: String,
    pub ui_scale_factor: f32,
    pub wifi_ssid: Option<String>,
    pub wifi_passphrase: Option<String>,
    pub telemetry_opt_in: bool,
}

impl SignedSystemConfig {
    pub fn new(user_name: &str, locale: &str, ui_scale_factor: f32) -> Self {
        Self {
            version: 1,
            user_name: user_name.to_string(),
            locale: locale.to_string(),
            ui_scale_factor,
            wifi_ssid: None,
            wifi_passphrase: None,
            telemetry_opt_in: false,
        }
    }

    pub fn to_bytes(&self) -> Result<Vec<u8>, bincode::Error> {
        bincode::serialize(self)
    }

    pub fn from_bytes(bytes: &[u8]) -> Result<Self, bincode::Error> {
        bincode::deserialize(bytes)
    }
}

pub struct PermissionManager {
    system_key: [u8; 32],
    active_config_digest: Arc<Mutex<Option<[u8; 32]>>>,
    active_config: Arc<Mutex<Option<SignedSystemConfig>>>,
}

impl PermissionManager {
    pub fn new() -> Self {
        // In production, loaded from kernel keyring or TPM nvram
        let system_key = [0x5A; 32];
        Self {
            system_key,
            active_config_digest: Arc::new(Mutex::new(None)),
            active_config: Arc::new(Mutex::new(None)),
        }
    }

    /// Verifies HMAC signature for updated configuration payloads from Settings
    pub fn verify_signed_config(&self, payload: &[u8], signature: &[u8; 32]) -> bool {
        let expected = self.compute_hmac(payload);
        expected == *signature
    }

    pub fn compute_hmac(&self, payload: &[u8]) -> [u8; 32] {
        let mut combined = Vec::with_capacity(self.system_key.len() + payload.len());
        combined.extend_from_slice(&self.system_key);
        combined.extend_from_slice(payload);

        let mut hash = [0u8; 32];
        let mut sum: u64 = 0xCBF29CE484222325;
        for (i, &byte) in combined.iter().enumerate() {
            sum ^= byte as u64;
            sum = sum.wrapping_mul(0x100000001B3);
            hash[i % 32] ^= (sum >> ((i % 8) * 8)) as u8;
        }
        hash
    }

    pub fn apply_config(&self, payload: &[u8], signature: &[u8; 32]) -> Result<SignedSystemConfig, String> {
        if !self.verify_signed_config(payload, signature) {
            return Err("Cryptographic signature verification failed for system config".into());
        }

        let config = SignedSystemConfig::from_bytes(payload)
            .map_err(|e| format!("Failed to deserialize system config payload: {}", e))?;

        let mut active_digest = self.active_config_digest.lock().unwrap();
        *active_digest = Some(*signature);

        let mut active_cfg = self.active_config.lock().unwrap();
        *active_cfg = Some(config.clone());

        Ok(config)
    }

    pub fn get_active_config(&self) -> Option<SignedSystemConfig> {
        self.active_config.lock().unwrap().clone()
    }
}

impl Default for PermissionManager {
    fn default() -> Self {
        Self::new()
    }
}
