[package]
name = "astrophage-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
astrophage-protocol = { path = "../protocol" }
amgos-protocol = { path = "../../amgos-protocol" }
serde = { workspace = true }
bincode = { workspace = true }
