[package]
name = "filer-shell"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
filer-protocol = { path = "../protocol" }
amgos-protocol = { path = "../../amgos-protocol" }
serde = { workspace = true }
bincode = { workspace = true }
winit = "0.30.13"
wgpu = "30.0.1"
crossbeam-channel = "0.5.17"
