name: AMGOS CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  workspace-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: Check Workspace
        run: cargo check --workspace --all-targets
      - name: Run Tests
        run: cargo test --workspace
      - name: Format Check
        run: cargo fmt --all -- --check
